<a href="https://colab.research.google.com/github/kashika9100/test1/blob/main/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
csv_l = pd.read_csv("/content/drive/MyDrive/data OPS lab 1/ODD.xlsx - Sheet1 (1).csv")
df = pd.DataFrame(csv_l)
df

,Booking_ID,Customer_ID,Destination,Travel_Dates,Booking_Date,Number_of_Travelers,Travel_Package,Payment_Method,Total_Cost,Travel_Agent,Customer_Feedback
0,BKG01438,CUST5663,BANGALORE,2024-05-27 - 2025-06-02,2023-07-26,3.0,Premium,Debit Card,41695.84,Bass Inc,Power matter brother guy. Out adult perhaps ge...
1,BKG02701,CUST4963,Vietnam,2024/05/02 / 2025/06/28,2024-02-05,3.0,Standard,Credit Card,36619.85,Wood Group,Position call within size than couple. Effect ...
2,BKG03648,cust5625,Tokyo,2023-12-02 - 2025-03-09,2024-07-17,2.0,NaN,NaN,44543.87,Bridges-Collins,NaN
3,BKG02513,CUST4246,Delhi,2023-11-10 - 2024-09-13,2024-03-15,6.0,Luxury,Credit Card,41053.94,"Edwards, Hill and Lee",NaN
4,bkg02903,CUST3901,Chennai,2023-11-09 - 2024-08-22,2023-04-09,3.0,Luxury,PayPal,36238.26,Hardy Inc,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5245,BKG03093,CUST4090,BRANDYVILLE,2024-01-23 - 2025-04-15,2024-08-17,3.0,NaN,Bank Transfer,45823.85,"King, Porter and Patrick",Understand man remain tough.
5246,BKG03773,CUST0249,SAINT LUCIA,2023-12-11 - 2025-01-11,2023-04-07,1.0,NaN,NaN,28937.40,Lane-Hopkins,Scientist bank wife. Measure prevent fear imag...
5247,bkg04354,CUST3227,Delhi,2024-06-13 - 2025-04-10,2024-04-15,6.0,Luxury,Bank Transfer,63021.04,Curry-Duke,Space area above score economy happy spring in...
5248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5249,BKG00861,CUST1529,Turkmenistan,2024-05-11 - 2024-11-06,2024-07-12,3.0,Standard,PayPal,77632.50,"Lewis, Jones and Morgan",NaN

In [49]:
print(df.groupby("Destination")["Total_Cost"].mean())

Destination
ALBANIA           73664.210000
ALEJANDROSHIRE    78168.730000
ARUBA              8573.290000
Adamsbury         22309.600000
Adamsfurt         15705.440000
                      ...
Zacharyberg       41751.850000
Zambia            20658.930000
Zamoramouth       84404.310000
Zimbabwe          31329.406667
Zimmermantown     59139.600000
Name: Total_Cost, Length: 858, dtype: float64

In [73]:
print(df["Destination"].drop_duplicates().count())
# OR
print(df["Destination"].nunique())

858
858

In [80]:
df["Booking_Date"] = pd.to_datetime(df["Booking_Date"])
df

,Booking_ID,Customer_ID,Destination,Travel_Dates,Booking_Date,Number_of_Travelers,Travel_Package,Payment_Method,Total_Cost,Travel_Agent,Customer_Feedback
0,BKG01438,CUST5663,BANGALORE,2024-05-27 - 2025-06-02,2023-07-26,3.0,Premium,Debit Card,41695.84,Bass Inc,Power matter brother guy. Out adult perhaps ge...
1,BKG02701,CUST4963,Vietnam,2024/05/02 / 2025/06/28,2024-02-05,3.0,Standard,Credit Card,36619.85,Wood Group,Position call within size than couple. Effect ...
2,BKG03648,cust5625,Tokyo,2023-12-02 - 2025-03-09,2024-07-17,2.0,NaN,NaN,44543.87,Bridges-Collins,NaN
3,BKG02513,CUST4246,Delhi,2023-11-10 - 2024-09-13,2024-03-15,6.0,Luxury,Credit Card,41053.94,"Edwards, Hill and Lee",NaN
4,bkg02903,CUST3901,Chennai,2023-11-09 - 2024-08-22,2023-04-09,3.0,Luxury,PayPal,36238.26,Hardy Inc,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5245,BKG03093,CUST4090,BRANDYVILLE,2024-01-23 - 2025-04-15,2024-08-17,3.0,NaN,Bank Transfer,45823.85,"King, Porter and Patrick",Understand man remain tough.
5246,BKG03773,CUST0249,SAINT LUCIA,2023-12-11 - 2025-01-11,2023-04-07,1.0,NaN,NaN,28937.40,Lane-Hopkins,Scientist bank wife. Measure prevent fear imag...
5247,bkg04354,CUST3227,Delhi,2024-06-13 - 2025-04-10,2024-04-15,6.0,Luxury,Bank Transfer,63021.04,Curry-Duke,Space area above score economy happy spring in...
5248,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
5249,BKG00861,CUST1529,Turkmenistan,2024-05-11 - 2024-11-06,2024-07-12,3.0,Standard,PayPal,77632.50,"Lewis, Jones and Morgan",NaN

In [105]:
# values not being reasonable means NaN - Not a Number  values
print(df["Number_of_Travelers"].isna().count())

5250
Booking_ID             5200
Customer_ID            5200
Destination            5200
Travel_Dates           5200
Booking_Date           5200
Number_of_Travelers    5200
Travel_Package         3769
Payment_Method         4161
Total_Cost             4937
Travel_Agent           4471
Customer_Feedback      2624
dtype: int64