<a href="https://colab.research.google.com/github/kashika9100/test1/blob/main/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
lab_file = pd.read_csv("/content/drive/MyDrive/data OPS lab 1/Even.xlsx - messy_2_employee_data (1).csv")
df = pd.DataFrame(lab_file)
df

,Employee_Name,Employee_ID,Job_Role,Phone_Number,Email_ID,Total_Work_Hour_per_Month,Salary_per_Month
0,Jane Miller,8797,Developer,3.801881e+09,emily.taylor@example.com,9999.0,NaN
1,Michael Brown,6540,Manager,7.904752e+09,john.brown@test.net,160.0,11200.0
2,Sarah Anderson,2353,Developer,9.463822e+09,sarah.wilson@sample.org,9999.0,-5000.0
3,Chris Johnson,6392,Engineer,8.727628e+09,john.jones@sample.org,160.0,8000.0
4,Laura Smith,1653,Analyst,7.750284e+08,sarah.taylor@test.net,9999.0,NaN
...,...,...,...,...,...,...,...
95,Emily Smith,5111,NaN,4.463884e+09,james.davis@test.net,-10.0,100000.0
96,Sarah Wilson,7388,Engineer,7.455009e+09,john.johnson@example.com,NaN,100000.0
97,NaN,3773,Manager,4.515526e+08,david.miller@sample.org,NaN,100000.0
98,Sarah Smith,1442,Analyst,3.294945e+09,jessica.anderson@example.com,-10.0,-5000.0
99,Michael Jones,3490,Analyst,9.425622e+09,john.miller@sample.org,NaN,NaN

In [ ]:
print(df["Job_Role"].drop_duplicates().count())

5

In [ ]:
print(df["Employee_ID"].duplicated().count())

100

In [ ]:
#wherever we have salary as -5000 it is converted to 0
df[df["Salary_per_Month"] == -5000] = 0
df

,Employee_Name,Employee_ID,Job_Role,Phone_Number,Email_ID,Total_Work_Hour_per_Month,Salary_per_Month
0,Jane Miller,8797,Developer,3.801881e+09,emily.taylor@example.com,9999.0,NaN
1,Michael Brown,6540,Manager,7.904752e+09,john.brown@test.net,160.0,11200.0
2,0,0,0,0.000000e+00,0,0.0,0.0
3,Chris Johnson,6392,Engineer,8.727628e+09,john.jones@sample.org,160.0,8000.0
4,Laura Smith,1653,Analyst,7.750284e+08,sarah.taylor@test.net,9999.0,NaN
...,...,...,...,...,...,...,...
95,Emily Smith,5111,NaN,4.463884e+09,james.davis@test.net,-10.0,100000.0
96,Sarah Wilson,7388,Engineer,7.455009e+09,john.johnson@example.com,NaN,100000.0
97,NaN,3773,Manager,4.515526e+08,david.miller@sample.org,NaN,100000.0
98,0,0,0,0.000000e+00,0,0.0,0.0
99,Michael Jones,3490,Analyst,9.425622e+09,john.miller@sample.org,NaN,NaN

In [ ]:
df["Total_Work_Hour_per_Month"].fillna(0)
df["Salary_per_Month"].fillna(0)
df["Hourly_Wage"] = df["Salary_per_Month"]/df["Total_Work_Hour_per_Month"]
df

,Employee_Name,Employee_ID,Job_Role,Phone_Number,Email_ID,Total_Work_Hour_per_Month,Salary_per_Month,Hourly_Wage
0,Jane Miller,8797,Developer,3.801881e+09,emily.taylor@example.com,9999.0,NaN,NaN
1,Michael Brown,6540,Manager,7.904752e+09,john.brown@test.net,160.0,11200.0,70.0
2,0,0,0,0.000000e+00,0,0.0,0.0,NaN
3,Chris Johnson,6392,Engineer,8.727628e+09,john.jones@sample.org,160.0,8000.0,50.0
4,Laura Smith,1653,Analyst,7.750284e+08,sarah.taylor@test.net,9999.0,NaN,NaN
...,...,...,...,...,...,...,...,...
95,Emily Smith,5111,NaN,4.463884e+09,james.davis@test.net,-10.0,100000.0,-10000.0
96,Sarah Wilson,7388,Engineer,7.455009e+09,john.johnson@example.com,NaN,100000.0,NaN
97,NaN,3773,Manager,4.515526e+08,david.miller@sample.org,NaN,100000.0,NaN
98,0,0,0,0.000000e+00,0,0.0,0.0,NaN
99,Michael Jones,3490,Analyst,9.425622e+09,john.miller@sample.org,NaN,NaN,NaN