<a href="https://colab.research.google.com/github/kashika9100/test1/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
#updatedcode1
#updated code
import pandas as pd

df=pd.read_excel("/content/drive/MyDrive/data operations/Session1_Exercise (2).xlsx")
print(df)
# as its extension is .xlsx so we use 'read_excel' like 'read_csv'
#use 'names' for chanding col index

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]

In [ ]:
#EXAMPLECODE
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       1000 non-null   object
 1   B       1000 non-null   object
 2   C       1000 non-null   object
 3   D       1000 non-null   object
 4   E       1000 non-null   object
 5   F       1000 non-null   int64
 6   G       1000 non-null   int64
 7   H       1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

df.isnull().sum()  or         df.isna().sum()


 gives  you   the   sum   of   the  null   values   present   in  each  col   like   names  col   has  19   null  values  ,  etc.

In [ ]:
df.describe()

       math score  reading score  writing score
count  997.000000     997.000000     997.000000
mean    66.056169      69.119358      68.003009
std     15.165514      14.583949      15.183582
min      0.000000      17.000000      10.000000
25%     57.000000      59.000000      57.000000
50%     66.000000      70.000000      69.000000
75%     77.000000      79.000000      79.000000
max    100.000000     100.000000     100.000000

In [ ]:
df["Total"] = df[["math score","reading score","writing score"]].sum(axis=1)
df["Maximum"] = df[["math score","reading score","writing score"]].max(axis=1)
df["Minimum"] = df[["math score","reading score","writing score"]].min(axis=1)
df["Average"] = df[["math score","reading score","writing score"]].mean(axis=1)
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score  total  \
0                      none          72             72             74    218
1                 completed          69             90             88    247
2                      none          90             95             93    278
3                      none          47             57             44    148
4                      none          76             78             75    229
..                      ...         ...            ...            ...    ...
995               completed          88             99             95    282
996                    none          62             55             55    172
997               completed          59             71             65    195
998               completed          68             78             77    223
999                    none          77             86             86    249

     Total  Maximum  Minimum    Average
0      218       74       72  72.666667
1      247       90       69  82.333333
2      278       95       90  92.666667
3      148       57       44  49.333333
4      229       78       75  76.333333
..     ...      ...      ...        ...
995    282       99       88  94.000000
996    172       62       55  57.333333
997    195       71       59  65.000000
998    223       78       68  74.333333
999    249       86       77  83.000000

[1000 rows x 13 columns]

In [ ]:
df_sorted = df.sort_values(by="Average",ascending=False)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total,Total,Maximum,Minimum,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,218,74,72,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,247,90,69,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,278,95,90,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,148,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,229,229,78,75,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,282,99,88,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,172,62,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,195,71,59,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,223,78,68,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,249,86,77,83.000000

In [ ]:
import pandas as pd
df=pd.DataFrame({"names":["a","b","c","d","e","f","g"],"age":[1,2,1,3,4,5,6],"marks":[12,13,14,15,16,17,18]})
df.insert(1,"wear",[1,2,3,4,5,6,7])

print(df)

  names  wear  age  marks
0     a     1    1     12
1     b     2    2     13
2     c     3    1     14
3     d     4    3     15
4     e     5    4     16
5     f     6    5     17
6     g     7    6     18